### PR TITLE
fix: proxy value in example

### PR DESCRIPTION
**Pull request by harmyderoman**

### CODE REVIEW

**Comment by wobsoriano** [comment]
`.value` isn't needed in templates.

Screenshot 2023-01-06 at 5 57 11 PM

**Comment by harmyderoman** [comment]
But why does it work for me? It fixed my code.

**Comment by huzaifahj** [comment]
Same here, weird

**Comment by harmyderoman** [comment]
> `.value` isn't needed in templates.
> 
> Screenshot 2023-01-06 at 5 57 11 PM

Yes, it unrefs in templates, but it's not true for nested `ref`. In your example, you destruct data from the query, so it works. But in the docs, you don't. So these are two choices to make it works, add `.value` in a template or destruct it after getting from the query.

**Pull request closed without merging**
